[package]
name = "mgbfs-runtime"
version = "0.1.0"
edition = "2021"
rust-version = "1.75"

[features]
cuda = ["dep:mgbfs-cuda", "mgbfs-cuda/cuda"]

[dependencies]
mgbfs-core = { path = "../mgbfs-core" }
sha2 = "=0.10.8"
mgbfs-cuda = { path = "../mgbfs-cuda", optional = true }

[[example]]
name = "single_gpu_bench"
required-features = ["cuda"]

[[example]]
name = "native_bench"
required-features = ["cuda"]
