use mgbfs_core::{graph_definition::{GraphDefinitionV2,GraphAction},Result};
pub(crate) fn requested()->Result<bool>{match std::env::var("MGBFS_GENERIC_GENERATOR").as_deref(){Ok("gemm")=>Ok(true),Ok("cuda")|Err(_)=>Ok(false),_=>Err("INVALID_GENERIC_GENERATOR".into())}}
pub(crate) fn eligible(graph:&GraphDefinitionV2)->bool{match &graph.action{GraphAction::Permutation{degree,generators}=>*degree>0&&*degree<=64&&!generators.is_empty()&&generators.len()<=64&&graph.start.iter().all(|v|(0..=255).contains(v)),GraphAction::Matrix{rows,cols,generators}=>*rows>=8&&*rows<=64&&*rows%8==0&&*cols>0&&*cols<=64&&!generators.is_empty()&&generators.len()<=64&&generators.iter().all(|g|(1..=256).contains(&g.modulo)&&g.matrix.iter().all(|v|(0..=255).contains(v)))&&graph.start.iter().all(|v|(0..=255).contains(v))}}
// Conservative SoA/GEMM staging reserve; padding is included before allocation.
pub(crate) fn workspace(elements:u32,g:u32,batch:u32)->Result<u64>{if !requested()?{return Ok(0);}let n=elements.min(64);let padded=(n+15)/16*16;let columns=(g*n+7)/8*8;u64::from(batch).checked_mul(u64::from(elements)).and_then(|x|x.checked_mul(1+4*u64::from(g)+32)).and_then(|x|x.checked_add((u64::from(padded)+28)*u64::from(columns))).ok_or_else(||"GEMM_WORKSPACE_OVERFLOW".into())}
#[cfg(feature="cuda")]
pub(crate) struct Context{pub ptr:*mut std::ffi::c_void,device:i32}
#[cfg(feature="cuda")]
impl Context{pub fn new(graph:&GraphDefinitionV2,batch:u32,device:i32)->Result<Self>{if !eligible(graph){return Err("GEMM_GRAPH_NOT_EXACTLY_SUPPORTED".into());}let(n,m,g,values)=match &graph.action{GraphAction::Matrix{rows,cols,generators}=>(*rows,*cols,generators.len() as u32,generators.iter().flat_map(|g|g.matrix.iter().copied()).collect::<Vec<_>>()),GraphAction::Permutation{degree,generators}=>{let n=*degree as usize;let mut values=vec![0i64;generators.len()*n*n];for(gen,permutation)in generators.iter().enumerate(){for(row,&column)in permutation.iter().enumerate(){values[gen*n*n+row*n+column as usize]=1;}}(*degree,1,generators.len() as u32,values)}};let mut ptr=std::ptr::null_mut();crate::generic_native::check(unsafe{mgbfs_cuda::generic_graph::mgbfs_generic_gemm_create(n,m,g,batch,values.as_ptr(),&mut ptr)})?;Ok(Self{ptr,device})}}
#[cfg(feature="cuda")]
impl Drop for Context{fn drop(&mut self){unsafe{mgbfs_cuda::native_owner::cudaSetDevice(self.device);mgbfs_cuda::generic_graph::mgbfs_generic_gemm_destroy(self.ptr);}}}
