//! Native scheduling contracts. CPU models are verification tools, not GPU fallbacks.
pub mod archive;
pub mod benchmark;
pub mod control_connection;
pub mod control_handshake;
pub mod control_wire;
#[cfg(feature = "cuda")]
pub mod dense_device;
pub mod distributed_memory;
#[cfg(feature = "cuda")]
pub mod distributed_native;
pub mod exchange;
pub mod failure;
#[cfg(feature = "cuda")]
pub mod hash_first_exchange;
pub mod jobs;
#[cfg(feature = "cuda")]
pub mod macro_native;
pub mod macro_owner;
pub mod macro_simulation;
#[cfg(feature = "cuda")]
pub mod native;
pub mod owner;
#[cfg(feature = "cuda")]
pub mod pinned_archive;
pub mod receipts;
pub mod ring;
pub mod simulation;
pub mod topology;
pub mod transport;
