// Real production reseed/retire with sparse virtual memory: high row and slot,
// three physical allocation pages, not a giant VRAM allocation.
#include <cuda.h>
#include <cuda_runtime.h>
#include <cstdint>
#include <cstdio>
#include <stdexcept>
#include "generic_visited.h"
extern "C" int mgbfs_generic_reseed_rows_u8_wide(uint32_t,const uint8_t*,uint32_t,uint32_t,uint32_t,uint64_t*,uint64_t,uint64_t*,uint64_t,uint32_t,uint32_t*,void*);
extern "C" int mgbfs_generic_retire_rows_wide(uint64_t*,uint64_t,const uint64_t*,uint32_t,uint32_t,uint32_t,uint32_t*,void*);
void ck(CUresult r){if(r!=CUDA_SUCCESS)throw std::runtime_error("driver "+std::to_string(r));}
void rt(cudaError_t r){if(r)throw std::runtime_error(cudaGetErrorString(r));}
uint64_t mix(uint64_t x){x^=x>>30;x*=0xbf58476d1ce4e5b9ULL;x^=x>>27;x*=0x94d049bb133111ebULL;return x^(x>>31);}
struct Sparse{CUdeviceptr base=0,mapped=0;size_t size=0,page=0;CUmemGenericAllocationHandle h=0;Sparse(uint64_t bytes,uint64_t offset,int device){CUmemAllocationProp p{};p.type=CU_MEM_ALLOCATION_TYPE_PINNED;p.location={CU_MEM_LOCATION_TYPE_DEVICE,device};ck(cuMemGetAllocationGranularity(&page,&p,CU_MEM_ALLOC_GRANULARITY_MINIMUM));size=(bytes+page-1)/page*page;ck(cuMemAddressReserve(&base,size,page,0,0));ck(cuMemCreate(&h,page,&p,0));mapped=base+offset/page*page;ck(cuMemMap(mapped,page,0,h,0));CUmemAccessDesc a{};a.location=p.location;a.flags=CU_MEM_ACCESS_FLAGS_PROT_READWRITE;ck(cuMemSetAccess(mapped,page,&a,1));}~Sparse(){cuMemUnmap(mapped,page);cuMemRelease(h);cuMemAddressFree(base,size);}};
int main(){try{ck(cuInit(0));for(int d=0;d<2;d++){rt(cudaSetDevice(d));rt(cudaFree(nullptr));uint32_t row=0x80000005u,stride=0xfffffffdu;uint64_t slots=1ULL<<33;uint8_t value=255;uint64_t hash=mix(mix(value));uint64_t bucket=uint64_t((__uint128_t(hash)*slots)>>64);while(bucket<=0xffffffffu&&value){value--;hash=mix(mix(value));bucket=uint64_t((__uint128_t(hash)*slots)>>64);}if(bucket<=0xffffffffu)throw std::runtime_error("fixture bucket not wide");Sparse arena(stride,row,d),table(slots*8,bucket*8,d),positions(uint64_t(stride)*8,uint64_t(row)*8,d);uint64_t empty=~0ULL;uint32_t zero=0,*error;rt(cudaMalloc(&error,4));rt(cudaMemcpy((void*)(arena.base+row),&value,1,cudaMemcpyHostToDevice));rt(cudaMemcpy((void*)(table.base+bucket*8),&empty,8,cudaMemcpyHostToDevice));rt(cudaMemcpy(error,&zero,4,cudaMemcpyHostToDevice));if(mgbfs_generic_reseed_rows_u8_wide(1,(uint8_t*)arena.base,stride,row,1,(uint64_t*)table.base,slots,(uint64_t*)positions.base,0,64,error,nullptr))throw std::runtime_error("reseed launch");rt(cudaDeviceSynchronize());uint64_t actual=0,token=0;uint32_t fatal=0;rt(cudaMemcpy(&actual,(void*)(positions.base+uint64_t(row)*8),8,cudaMemcpyDeviceToHost));rt(cudaMemcpy(&token,(void*)(table.base+bucket*8),8,cudaMemcpyDeviceToHost));rt(cudaMemcpy(&fatal,error,4,cudaMemcpyDeviceToHost));if(fatal||actual!=bucket||uint32_t(token)!=row||(token>>63))throw std::runtime_error("wide reseed mismatch");if(mgbfs_generic_retire_rows_wide((uint64_t*)table.base,slots,(uint64_t*)positions.base,stride,row,1,error,nullptr))throw std::runtime_error("retire launch");rt(cudaDeviceSynchronize());rt(cudaMemcpy(&token,(void*)(table.base+bucket*8),8,cudaMemcpyDeviceToHost));rt(cudaMemcpy(&fatal,error,4,cudaMemcpyDeviceToHost));if(fatal||token!=empty-1)throw std::runtime_error("wide retire mismatch");rt(cudaFree(error));printf("VERIFIED device=%d row=%u slot=%llu physical_pages=3\n",d,row,(unsigned long long)bucket);}return 0;}catch(const std::exception& e){fprintf(stderr,"%s\n",e.what());return 1;}}
